version: '3.2'
services:
  config:
    image: "steeltoeoss/config-server:latest"
    ports:
      - "8888:8888"
    environment:
      - "LOGGING_LEVEL_ORG_SPRING_FRAMEWORK_CLOUD_CONFIG=TRACE"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/SteeltoeOSS/musicStore-config.git"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=src/config"
      - "SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/crdant/steeltoe-musicstore-config"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_LABEL=main"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=steeltoe,bob"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/crdant/spring-cloud-gateway-demo"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=config/{application}/{profile}"
      # - "SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=bob"
